### ISSUE TITLE
CLEAR INTRUCTIONS PLEASE

### ISSUE THREAD

**Issue by Alcross008** [doGior/Audible-Downloader#5]
Hello....Can you more clearly explain how to decrypt a .aax file after I have downloaded it onto my pc? How do I do this using your Audible Downloader? Thanks a million.

**Comment by doGior** [comment]
In order to run this script you have to be inside the terminal and navigate to the downloaded folder, from there you have to run `python3 main.py` and follow the instructions

Btw, this script automatically downloads and converts the files, if you only want to convert them you can copy the `ConvertToMp3` function and make a script out of it.

**Comment by Alcross008** [comment]
Ohh okay...so does this script just download audios which I pay for? Can
you tell me if there is a script to download any audio from Amazon without
paying for it? Thank you Sir.

**Comment by doGior** [comment]
I don't know, I simply added to my library as much shows as possible during the free trial and then downloaded them
