### ISSUE TITLE
Captcha but not showing image

### ISSUE THREAD

**Issue by YOZZOPANOZZO** [doGior/Audible-Downloader#7]
<img width="460" alt="image" src="https://user-images.githubusercontent.com/54823311/157100668-b5ae17a8-eaf5-45c7-b6c4-2ea0ee6534df.png">

**Comment by doGior** [comment]
Sorry I made this script in a couple of hours when I got the Audible trial and then I kinda forgot about it. 
Your problem is probably caused by a package that dependabot updated but that I didn't test since my audible test ended and I didn't renew it.

If you really want to use this script try a lower version of Pillow or read their documentation and try to fix the script
