### ISSUE TITLE
ModuleNotFoundError: No module named 'audible'

### ISSUE THREAD

**Issue by nevarDeath** [doGior/Audible-Downloader#8]
Hi, I'm using Python 3.10.4 on Windows 10. After cloning the repo and changing the download path in config.py, I ran main.py and got this error message about a missing module. I'm not sure what that means or how to fix it. Is this possibly because of a missing dependency?

```
C:\FilePath\Audible-Downloader> python main.py
Traceback (most recent call last):
  File "C:\FilePath\Audible-Downloader\main.py", line 1, in <module>
    import audible, httpx, os, subprocess, asyncio, config
ModuleNotFoundError: No module named 'audible'
```

**Comment by doGior** [comment]
Sorry I made this script in a couple of hours when I got the Audible trial and then I kinda forgot about it.

It seems that you skipped a part: `pip install -r requirements.txt`.
If you're sure you did it, the problem could be in the requirements file, try removing `pkg-resources==0.0.0`.

Btw I'm gonna archive this script since it's old and it's really a mess
